- name: "Pycharm | Cli | Set client version year"
  ansible.builtin.set_fact:
    pycharm_cli_client_version_year: "{{ pycharm.cli.version.split('.')[0] | int }}"
  when:
    - pycharm.cli is defined

- name: "Pycharm | Cli | Set cli client edition path"
  ansible.builtin.set_fact:
    pycharm_cli_client_path: "{{ pycharm_path }}/{{ pycharm.cli.edition }}/{{ pycharm_cli_client_version_year }}"
  when:
    - pycharm.cli is defined or (pycharm.remove is defined and pycharm.remove)

- name: "Pycharm | Cli | Stat cli client edition directory"
  ansible.builtin.stat:
      path: "{{ pycharm_cli_client_path }}"
  register: pycharm_cli_client_dir_stat
  when:
    - pycharm.cli is defined
    - pycharm.cli.remove is undefined or not pycharm.cli.remove


- name: "Pycharm | Cli | Create symlink to binary"
  ansible.builtin.file:
    src: "{{ pycharm_cli_client_path }}/bin/{{ 'pycharm.sh' if (pycharm.cli.launcher == 'script') else 'pycharm' }}"
    dest: "/usr/bin/pycharm"
    owner: "root"
    group: "root"
    mode: 0755
    state: link
  when:
    - pycharm.cli is defined
    - pycharm.cli.remove is undefined or not pycharm.cli.remove
    - pycharm.remove is undefined or not pycharm.remove
    - pycharm_cli_client_dir_stat is defined
    - not (pycharm_cli_client_dir_stat.skipped | default(false))
    - pycharm_cli_client_dir_stat.stat.exists

- name: "Pycharm | Cli | Remove symlink to binary"
  ansible.builtin.file:
    path: "/usr/bin/pycharm"
    state: absent
  when:
    - (pycharm.cli is defined and pycharm.cli.remove is defined and pycharm.cli.remove) or (pycharm.remove is defined and pycharm.remove) or (pycharm_cli_client_dir_stat is defined and not (pycharm_cli_client_dir_stat.skipped | default(false)) and not pycharm_cli_client_dir_stat.stat.exists)
