---
# The following role attempts to download any requested PyCharm
# clients and configure them.

- name: Assert task variables
  tags: assert,jetbrains,pycharm
  ansible.builtin.import_tasks: assertions/assert.yml
  run_once: yes
  delegate_to: localhost


- name: Download clients
  tags: software,download,jetbrains,pycharm
  ansible.builtin.include_tasks: download.yml
  loop: "{{ pycharm.clients }}"
  loop_control:
    loop_var: client
  when: pycharm.clients | length > 0


- name: Download clients
  tags: software,download,jetbrains,pycharm
  ansible.builtin.include_tasks: download.yml
  vars:
    client: pycharm.cli
  when: pycharm.cli exists
