---
# The following role attempts to download any requested PyCharm
# clients and configure them.

- name: Assert task variables
  tags: assert,jetbrains,pycharm
  ansible.builtin.import_tasks: assertions/assert.yml
  run_once: yes
  delegate_to: localhost


- name: Download clients
  tags: software,download,jetbrains,pycharm
  ansible.builtin.include_tasks: download.yml
  loop: "{{ pycharm_clients }}"
  loop_control:
    loop_var: client
  when: pycharm_clients | length > 0
