---
# This file contains tasks for adding a PyCharm client to the global path

- name: Stat client version directory
  ansible.builtin.stat:
      path: "{{ pycharm_path }}/{{ client.edition }}/{{ client.version }}"
  register: client_version_dir


- name: Symlink client binary
  ansible.builtin.file:
    src: "{{ client_version_dir.stat.path }}/bin/pycharm.sh"
    dest: "/usr/bin/pycharm"
    owner: "root"
    group: "root"
    mode: 0755
    state: link
  when:
    - client_version_dir.stat.exists
